// 畫面上出現的文字，集中在這裡（對應 docs/design.md 第 5 節）。
import { MESSAGE_MAX, NICKNAME_MAX, KEEP_COUNT } from './config'

export const T = {
  appName: '匿名聊天室',
  tagline: '不用登入，用代號就能聊',
  joinIntro1: '不用登入，取個代號就能加入。',
  joinIntro2: '所有人都在同一個聊天室裡。',
  nicknameLabel: '你的代號',
  nicknamePlaceholder: '輸入代號',
  nicknameHelp: `1～${NICKNAME_MAX} 個字，中英文、數字、emoji 都可以。`,
  enter: '進入聊天室',
  entering: '進入中…',
  errTaken: '這個代號已經有人用了，請換一個',
  errTooLong: `代號最多 ${NICKNAME_MAX} 個字`,
  errBlank: '代號不能是空白，也不能含看不見的字元',
  noticeLost: '連線中斷太久，代號已被他人使用，請重新輸入。',
  errUnavailable: '目前無法連線，請稍後再試。',
  onlineDesktop: (n: number) => `目前 ${n} 人在線`,
  onlineMobile: (n: number) => `${n} 人在線`,
  leave: '離開',
  retention: `只保留最近的 ${KEEP_COUNT} 則訊息`,
  newMessages: '有新訊息',
  composerPlaceholder: '輸入訊息…',
  composerHint: 'Enter 送出　Shift + Enter 換行',
  composerLabel: '訊息內容',
  send: '傳送訊息',
  reconnecting: '連線中斷，重新連線中…',
  membersTitle: '線上成員',
  membersCount: (n: number) => `${n} 人`,
  you: '（你）',
  collapseMembers: '收起名單',
  expandMembers: '展開線上名單',
  errSendTooLong: `訊息最多 ${MESSAGE_MAX} 個字`,
  errSendNotMember: '你已經不在聊天室了',
  errSendUnavailable: '目前無法送出，請稍後再試',
  showAll: '顯示全部',
  showLess: '收合',
}
